import { Providers } from "@/components/providers";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es-DO">
			<body
				className={cn(
					"max-w-screen overflow-x-hidden min-h-screen",
					inter.className,
				)}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
