import { Footer } from "@/components/footer";
import { Providers } from "@/components/providers";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es-DO">
			<body
				className={cn(
					"max-w-screen overflow-x-hidden text-foreground",
					inter.className,
				)}
			>
				<div className="text-center py-2 w-screen bg-primary text-background">
					Example Notify
				</div>

				<Providers>
					{children}
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
