import { Providers } from "@/components/providers";
import { Header } from "@/components/ui/Header";
import { Footer } from "@/components/ui/Footer";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es-DO">
			<body
				className={cn(
					"max-w-screen overflow-x-hidden min-h-screen",
					inter.className,
				)}
			>
				<header className="print:hidden relative min-w-screen h-28">
					<div className="fixed z-40">
						<Header />
					</div>
				</header>
				<Providers>
					{children}
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
